### max, min, argmax, argmin

In [2]:
import numpy as np

In [13]:
ranIntValue = np.random.randint(0,50,10)
ranIntValue

array([41, 19,  0, 21,  6, 49, 34,  5, 21, 22])

In [14]:
ranIntValue.max()

49

In [15]:
ranIntValue.argmax()#找到最大值的index

5

In [16]:
ranIntValue.min()

0

In [17]:
ranIntValue.argmin()#找到最小值的index

2

## Indexing-and-Selection

In [19]:
arr = np.arange(3,15)
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
arr[4]

7

In [21]:
arr[1:5]

array([4, 5, 6, 7])

In [22]:
arr[:5]

array([3, 4, 5, 6, 7])

In [24]:
arr[5:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [27]:
arr[-3:] = 99
arr

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 99, 99, 99])

In [ ]:
myList = list(range(7,15))
print(myList)
newList = myList[2:5]
print(newList)
newList[1] = 77
print("=======================")
print(myList)
print(newList)

[7, 8, 9, 10, 11, 12, 13, 14]
[9, 10, 11]
[7, 8, 9, 10, 11, 12, 13, 14]
[9, 77, 11]


In [35]:
arr2 = np.arange(1,11)
print(arr2)
newArray = arr2[:7]
print(newArray)
newArray[0] = 999
print("=======================")
print(arr2)
print(newArray)

[ 1  2  3  4  5  6  7  8  9 10]
[1 2 3 4 5 6 7]
[999   2   3   4   5   6   7   8   9  10]
[999   2   3   4   5   6   7]


## 索引二維陣列（矩陣）

一般格式是 **arr_2d[row][col]** 或 **arr_2d[row, col]**。我推薦使用逗號標記法以增加清晰度。

In [36]:
arra_2d = np.array(([5,10,15],
                    [20,25,30],
                    [19,18,45],
                    [26,29,32]) ) 

In [37]:
arra_2d[1]

array([20, 25, 30])

In [38]:
arra_2d[1][0]

20

In [39]:
arra_2d[1,0]

20

In [40]:
arra_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [19, 18, 45],
       [26, 29, 32]])

In [42]:
arra_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [43]:
arra_2d[2,:]

array([19, 18, 45])

## 條件選擇

In [44]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
bool_arr = arr > 4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [46]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

# NumPy 運算

In [48]:
arr = np.arange(0,10)
print(arr + arr)
print(arr - arr)
print(arr * arr)
print(arr*2)
print(arr**2)

[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[ 0  1  4  9 16 25 36 49 64 81]
[ 0  2  4  6  8 10 12 14 16 18]
[ 0  1  4  9 16 25 36 49 64 81]


## 陣列的摘要統計

NumPy 也提供了常見的摘要統計功能，如 <em>sum</em>（總和）、<em>mean</em>（平均值）和 <em>max</em>（最大值）。你可以將這些函數作為陣列的方法來調用。下面是如何使用這些統計方法的例子：

1. **np.sum(arr)** - 計算陣列 `arr` 中所有元素的總和。
2. **np.mean(arr)** - 計算陣列 `arr` 中所有元素的平均值。
3. **np.max(arr)** - 找出陣列 `arr` 中的最大元素。
4. **np.min(arr)** - 找出陣列 `arr` 中的最小元素。
5. **np.std(arr)** - 計算陣列 `arr` 中元素的標準差。
6. **np.var(arr)** - 計算陣列 `arr` 中元素的方差。

In [51]:
arr = np.arange(1,11)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr.sum()

45

In [52]:
arr.mean()

5.5

In [53]:
print(arr.var())
print(arr.std())

8.25
2.8722813232690143


#### 1. Import NumPy as np

In [55]:
import numpy as np

#### 2. 創建一個包含10個零的陣列

In [57]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. 創建一個包含10個1的陣列希望是5x2的

In [60]:
np.ones(10).reshape(5,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

#### 4. 產生10個5的陣列

In [61]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. 創建一個包含從10到50的整數的陣列

In [62]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. 要創建一個包含從10到50的所有偶數整數的陣列

In [63]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. 要創建一個3x3矩陣，其中包含從0到8的值

In [64]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 8. 要創建一個3x3的單位矩陣（identity matrix）

In [66]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

####  要使用 NumPy 生成一個介於0和1之間的隨機數

In [72]:
np.random.rand(1)

array([0.29438043])

#### 要使用 NumPy 生成一個包含25個從標準正態分布（平均值為0，標準差為1的正態分布）抽樣的隨機數陣列

In [73]:
np.random.randn(25)

array([-0.66840765, -0.17700296,  0.42634303, -1.49480919,  0.227392  ,
        2.06900875,  2.17394942,  1.09997693, -0.32547574,  0.98308135,
        1.92472003,  0.20196751,  0.82155239,  0.87084966,  1.50741475,
       -2.03893552, -1.32280027, -0.11511354,  0.51494442, -0.73383592,
        1.90221653, -1.57969662, -0.08475483, -0.14501639, -0.54246776])

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [75]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [77]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [82]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [83]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Series
Series與NumPy陣列非常相似（事實上它是建立在NumPy陣列對象之上的）。將NumPy陣列與Series區分開來的是，Series可以具有軸標籤，這意味著它可以通過標籤進行索引，而不僅僅是通過數字位置。它也不需要保存數字數據，可以保存任意的Python對象。


In [84]:
import pandas as pd

In [85]:
myIndx = ["USA","Canada","Mexico"]
myData = [1776,1867,1821]
myser = pd.Series(data = myData)
print(myser)

0    1776
1    1867
2    1821
dtype: int64


In [87]:
myuser = pd.Series(data=myData,index=myIndx)
myuser

USA       1776
Canada    1867
Mexico    1821
dtype: int64

In [88]:
import numpy as np
ran_data =  np.random.randint(0,100,4)
ran_data

array([66, 15, 43, 75])

In [93]:
names = ["Ken","Vivin","Lucy","Joy"]
ages = pd.Series(ran_data,names)
ages

Ken      66
Vivin    15
Lucy     43
Joy      75
dtype: int32

In [95]:
ags = {"Gigi":5,"Any":10,"Carlos":15}
afeSer = pd.Series(ags)
afeSer

Gigi       5
Any       10
Carlos    15
dtype: int64

In [100]:
q1 = {"Japan":80,"China":450,"India":200,"USA":250}
q2 = {"Brazil":100,"China":500,"India":210,"USA":260}
sales_Q1 = pd.Series(q1)
sales_Q2 = pd.Series(q2)
print(sales_Q1["Japan"])
print(sales_Q1[0])
print(sales_Q2["Brazil"])
#print(sales_Q1["Brazil"])

80
80
100


C:\Users\xvpow\AppData\Local\Temp\ipykernel_16648\1162550105.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(sales_Q1[0])


In [101]:
sales_Q2.keys()

Index(['Brazil', 'China', 'India', 'USA'], dtype='object')

In [102]:
sales_Q2 * 2

Brazil     200
China     1000
India      420
USA        520
dtype: int64

In [103]:
sales_Q1 + sales_Q2

Brazil      NaN
China     950.0
India     410.0
Japan       NaN
USA       510.0
dtype: float64

In [104]:
sales_Q1.add(sales_Q2,fill_value=0)#fill_value=0表示缺失值用0

Brazil    100.0
China     950.0
India     410.0
Japan      80.0
USA       510.0
dtype: float64

## DataFrames

In [105]:
import pandas as pd
import numpy as np
np.random.seed(101)
myData = np.random.randint(0,101,(4,3))
print(myData)

[[95 11 81]
 [70 63 87]
 [75  9 77]
 [40  4 63]]


In [106]:
myindex = ['CA','NY','AZ','TX']
mycolumns = ['Jan','Feb','Mar']

In [111]:
df = pd.DataFrame(data=myData)
df

0   1   2
0  95  11  81
1  70  63  87
2  75   9  77
3  40   4  63

In [113]:
df = pd.DataFrame(data=myData,index=myindex)
df

0   1   2
CA  95  11  81
NY  70  63  87
AZ  75   9  77
TX  40   4  63

In [114]:
df = pd.DataFrame(data=myData,index=myindex,columns=mycolumns)
df

Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63

* 描述
    * 一位服務員在一家餐廳工作幾個月期間記錄了他收到的每一筆小費的信息。他收集了幾個變量：

* 格式
    * 一個包含244行和7個變量的數據框

* 詳細信息
    * 小費金額（美元），
    * 账单金额（美元），
    * 付款者的性别，
    * 聚會中是否有吸烟者，
    * 一周中的哪一天，
    * 一天中的時間，
    * 聚會的人數。

總共記錄了244筆小費。這些數據在一系列商業統計案例研究中被報告（Bryant & Smith 1995）。

* 參考文獻
    * Bryant, P. G. 和 Smith, M (1995) Practical Data Analysis: Case Studies in Business Statistics. Homewood, IL: Richard D. Irwin Publishing:
    
* 注意：我們創建了一些包含假數據的額外列，包括姓名、信用卡號和付款ID。